### PR TITLE
Add requirements.txt, Ziegler Nichols Tuned Values

### PR DESCRIPTION
**Pull request by AetherPrior**
- Tuned PID, gives graphs as follows: 
Figure_1
- Tradeoff b/w late start by decreasing KI to ~2/25 yields:
Figure_2

### CODE REVIEW

**Review by sathvikswaminathan — COMMENTED** [review]
Super smooth. Looks good. I think the late start case is better because it stabilises a bit sooner

**Review by sathvikswaminathan — APPROVED** [review]
Super smooth. Code looks good. I think the late start case is better because it stabilizes a bit sooner.

**Comment by AetherPrior** [comment]
Will try to make an auto-tuner later to make life easier,  
Won't guarantee that it'll work for all cases, and it definitely isn't applicable for IRL use,but whenever we roll out a new model we can give out tuned values that way

**Comment by AetherPrior** [comment]
> Super smooth. Code looks good. I think the late start case is better because it stabilizes a bit sooner.

You didn't have to comment twice

**Comment by sathvikswaminathan** [comment]
Lite. Here goes my third comment

**Pull request merged**
